### ISSUE TITLE
Not playing any song (v1.0.2)

### ISSUE THREAD

**Issue by Sharrnah** [TwiN/discord-music-bot#3]
### Describe the bug

I tried the Bot today (latest docker image, v1.0.2), and unfortunately i don't get it to play any song.

For (probably) short songs like `!play what is love`, i only get `Unable to find video for query what is love: timed out` as response.
Not much more info in the server logs.

for most likely longer songs (which is a surprising amount when searching on youtube. many videos are 1 hour or longer with multiple songs)
It gives me `Unable to find video for query epic music: failed to unmarshal video metadata: unexpected end of JSON input`

I was able to get it to at least _try_ to play "what is love", the bot joined but immediately left the voice channel again and said it finished. But that was a single occurrence till now.

Restarting does not help.

Also playing youtube links directly does not work (in the hope that this might help that it does not need to search first)

### What do you see?

responses like:
-  timed out
- failed to unmarshal video metadata: unexpected end of JSON input

### What do you expect to see?

bot to join the voicechannel i am in and start playing the music

### List the steps that must be taken to reproduce this issue

1. Install the Bot and add it to your Discord Server
2. Join a Voice-Channel
3. use a play command

### Version

v1.0.2

### Additional information

Running it inside a Kubernetes Cluster, just like https://github.com/eritislami/evobot

**Comment by TwiN** [comment]
It's possible; I haven't used this in a while. Can you try to re-build the docker image and tell me if it works? The Dockerfile has a step that retrieves the latest version of youtubedl, and that binary being outdated is usually the problem

**Comment by Adklps** [comment]
I have the same problem.I've installed it via portrainer and it times out no matter how many times I rebuild it.

**Comment by BomberH99** [comment]
did u ever find a fix for this?

**Comment by k4reash** [comment]
same problem here

**Comment by TwiN** [comment]
Seems like it's related to https://github.com/ytdl-org/youtube-dl/issues/30102

I'm going to update the Dockerfile & make a few changes to switch to https://github.com/yt-dlp/yt-dlp instead

**Comment by TwiN** [comment]
There seems to be another issue besides for this - the bot joins and then shortly after, leaves. 
I don't really have time to work on this project right now, so if fixing this is a pressing matter for somebody, you might have to look into it yourself 😔
